### ISSUE TITLE
Develop in Funding Source - Direct and Original donor 

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1051]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-56ad0dac6b41b55dbd8f0e9376c59593193e13f08458238240d1006a9ade5505.png)
task

**Comment by htobon** [comment]
The rules will be as follows:
1.	Original Donor is required.
2.	Direct Donor is optional.
3.	Original Donor and Direct donor must be different.

**Comment by AndresFVR** [comment]
@sebas932 will work at front-end to make Original Donor and Direct donor different..

**Comment by AndresFVR** [comment]
Added directDonor on FundingSources Pentaho report

**Comment by AndresFVR** [comment]
@htobon this develop has been moved to Marlo-Development to review.

**Comment by sebas932** [comment]
@htobon please remember to check this development in MARLO Dev, the improvements were applied.

**Comment by htobon** [comment]
Hi guys, we have been receiving some feedbacks from MARLO-Family. I'm curious to know if you have looked at them?

**Comment by sebas932** [comment]
@htobon those feedback comments were implemented and i sent an email to you

**Comment by sebas932** [comment]
@htobon please let me know if is there anything else pending in this issue

**Comment by htobon** [comment]
Can you please make this field for 50 words maximum?
Thank you in advance.

**Comment by htobon** [comment]
Hi guys, as per a set of feedbacks received from July 21st. Please make the following changes/improvements:

- [ ] **Pascale**: For consistency of capitalization, replace “Principal investigator” by “Principal Investigator”, and “if different from original donor” by “if different from Original Donor”.
- [ ] **Pascale**: Also, suggest replacing “If you can’t find the partner you are looking for” by “If you can’t find the donor you are looking for” for added clarity.
- [ ] **Pascale**: Replace “No lead partner added yet” by “No partner added yet”.
- [ ] **Hector**: Please make sure the extension date is only being displayed when synchronizing with CIAT-OCS. Otherwise, it should not appear.
- [ ] **Hector**:  In Start/End date, since we are not asking for days, we should not display them in the field ([See screenshot](https://www.screencast.com/t/Xf0Us56gIl)).
- [ ] **Grant**: Please swap around the Agreement status and Funding Window.
- [ ] **Grant**: Please include a description for the "Principal Investigator" field as follows: _"Researcher from the lead partner who is responsible for the research under this funding source"_
- [ ] **Pascale**: Develop an specificity for PIM as follows: 
> the status should only be “ongoing” for all sources of funding (because we don’t want to record proposals that have not been materialized through a contract in MARLO). Thanks to your comment I am now noticing that for W3, bilateral, and Center funds, there are two other options available. Hector, can you please remove these options for PIM?
