### ISSUE TITLE
SUMMARY - To Create a OnGoing, Active Projects Report in Pentaho

### ISSUE THREAD

**Issue by jurodca** [CCAFS/MARLO#1121]
Create a summary report that display the current list of projects in MARLO.

**Comment by htobon** [comment]
Hi Julia, please refer to the following feedback:

1. [ ] ![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e56abd651d1d91bb7b56d3ffeae205403a935a834c3ac4efae4c5ea6600a3266.png)

2. [ ] ![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1b47a7dd07417571ad4309b932987c98842dfcee66ae2b7bb2591d27e66eca55.png)

3. [ ] ![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0943e514d83593413fc7e2a4f94c04bee71ebd3045745f89581ec0451d5fab54.png)

4. [ ] ![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ad48c60d1b020f12a552eb5d685b41b7df72c543182b290753d6e530973c51fc.png)

5. [ ] Please include the following columns:
  - [ ] List of project coordinators (names and emails separated by commas).
  - [ ] Cluster of activities (just the acronyms separated by commas)
  - [ ] Cross-cutting dimensions:
    - [ ] Gender (Yes/No)
    - [ ] Youth  (Yes/No)
    - [ ] Capacity Development  (Yes/No)

**Comment by AndresFVR** [comment]
We have created a prototype of this report (see commit: https://github.com/CCAFS/MARLO/commit/ded0659ee5c0c95d10a2ff9b102545ea494e3c7d)

Refer to the following document: [https://app.zenhub.com/files/58572044/717cb906-d774-4476-9e5e-dd584b027ffc/download](https://app.zenhub.com/files/58572044/717cb906-d774-4476-9e5e-dd584b027ffc/download)

@jurodca, can you please send us a example of the report that you were developing in order to improve the actual?

**Comment by jurodca** [comment]
Here is an example of the report.

[OnGoingActiveProjectsSummary-2017_20170918-1024.xlsx](https://github.com/CCAFS/MARLO/files/1921443/OnGoingActiveProjectsSummary-2017_20170918-1024.xlsx)
