### ISSUE TITLE
BUG: FTA - When registering users for FTA some users did not receive notifications

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1187]
When registering users for FTA a number of users did not receive any notifications.  The types of users registered were:

- flagship leaders
- flagship managers
- cluster leaders 
- PMU team

So far we know that at least 1 cluster leader (the person is a new MARLO user) and 1 flagship leader (existing MARLO user) did not receive any emails.  Other flagship leaders and cluster leaders did receive the emails however.  Waiting for feedback from other team members to see if other categories of users also did not receive any emails.

**Comment by htobon** [comment]
Hi @Grant-Lay, I'm checking our list of issues and get into this one.

Let me describe a context of what it is currently happening:
We recently changed our Email provider since we were experiencing some issues when sending emails automatically. Here is the note: https://marlo-news.blogspot.com.co/2017/05/email-service-provider-updated.html

Unfortunately, we continue experiencing this kind of issues, even with another better Email provided.
So, we have been in conversation with the CIAT-IT team and they suggested us to improve the architecture of our server. The proposal is described in the issue #1195 (Sorry for the spanish). This was a message sent from one of the guys who usually help us on server stuffs.

Unfortunately, they do not have the time to implement it. 

That's why I was thinking that perhaps there is something we can develop at our end.
I proposed the technical team to storage in a database table, all the emails that MARLO is sending, and, if there is any email that could not be sent due to problems in the Email provider, we could mark it with some status (incomplete or pending) and perhaps we could run a proccess every 4 or 6 hours for MARLO to try to send the pending emails again.

Again, due to the short time we have a the moment, we have not had the opportunity to tackle this issue. Thus, I'm going to move this for our next sprint (from Jan 22nd) so we can discuss this in more detail soon.

**Comment by htobon** [comment]
As per conversation with @cgarcia9106, the first step would be to at least storage the emails in a table.

**Comment by cgarcia9106** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-6a8b6f712c6e6dfcb0a4f5ef552ca9d7e0a231b825b693b584b373b76ea17148.png)

**Comment by cgarcia9106** [comment]
on table email_logs will be registered the track of the emails

**Comment by cgarcia9106** [comment]
@htobon ya este desarrollo esta en produccion

**Comment by htobon** [comment]
Thank you @cgarcia9106. So I guess the next step would be to create a functionality that allow us to send the missing emails manually. So. I'll move this issue to the next milestones.

**Comment by cgarcia9106** [comment]
@sebas932 esperando el action
