### ISSUE TITLE
POWB Section 1.2 Expected CRP Progress Towards Intermediate Outcomes and SLOs

### ISSUE THREAD

**Issue by cgarcia9106** [CCAFS/MARLO#1266]
![image](https://user-images.githubusercontent.com/5375915/35570688-ed660a42-059d-11e8-8bec-04a2aaa55e7f.png)

![image](https://user-images.githubusercontent.com/5375915/35570714-f8dc6614-059d-11e8-9a1b-a13b8e900c72.png)

**Comment by htobon** [comment]
Hi @cgarcia9106, here is my feedback:

- [ ] Milestones texts are not ok. Please refer to the number at the end of each statement.
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/6fa75cf7-4c0e-4db2-966a-aa0248d5ddaa)

- [ ] There is a critical issue at project level when trying to include a new milestone contribution. Please fix this issue in order to continue moving ahead with the test.

- [ ] Please increase the width of the column "Means of verification"
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/00b7679b-b2fe-458a-8600-ea9303be3f35)
