### ISSUE TITLE
POWB Synthesis - Section 1.4 Plans by CRP Flagships

### ISSUE THREAD

**Issue by AndresFVR** [CCAFS/MARLO#1267]
- [x] Create model
- [x] Create Action: Prepare, Save
- [x] Create Validator
- [x] Create migration for permissions
- [x] Update Autosave and Historic
- [x] Create Method for Pentaho
- [x] Test in MARLOdev

![image](https://user-images.githubusercontent.com/5375915/35570758-1e34e31e-059e-11e8-9d99-ef638432e5d6.png)

**Comment by htobon** [comment]
Hi @AndresFVR, please refer to my feedback after testing below:

- [ ] Keep format
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/40782b42-be60-45b4-b22d-3b44410ad86b)

- [ ] Please also keep in mind that, since PMU does not need to do anything there, the green check mark should appear by default.

**Comment by htobon** [comment]
- [ ] Include a text when PMU visits this section.
![image.png](https://images.zenhubusercontent.com/57741a6dbf93871ccd9d5f48/8232580b-3716-4813-a49d-a47d2cfa5183)

**Comment by htobon** [comment]
Good job.
