### ISSUE TITLE
center_user_permissions view is broken in staging

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1284]
The center_user_permissions view is broken and references column research_area_id instead of the new global_unit_id column.

Please create a flyway script and link the commit to this issue so that I know how to fix broken views in the future.

**Comment by HermesJim** [comment]
Hi @Grant-Lay 
The center_user_permissions is no longer used. We had not deleted the view since it was not causing problems. anyway, I uploaded the migration script where it deletes the view.

**Comment by htobon** [comment]
Hi @Grant-Lay, thanks for spotting this.
As @HermesJim mentioned above, we have deleted the view since it is not needed any more.
https://github.com/CCAFS/MARLO/commit/ceb4620da0625dbc4fff21e82bb12730e2eff4cf

With regards how to update a database view, it seems there is no way to do this, thus, I think you should delete it, and re-create it again.

something like:
*DROP VIEW IF EXISTS....*
*CREATE VIEW.....*
