### ISSUE TITLE
What is the expected behaviour when we update a project/funding source in a previous phase

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1302]
When a user in a previous phase (say 2017 planning) creates a project or funding source, this information gets copied to future phases when they press save.  

My question is when a user then updates information in the previous phase (2017 planning), are the updates expected to be propagated to future phases (e.g. 2018)?

**Comment by htobon** [comment]
Hi @Grant-Lay, the idea is that everything you do in planning 2017 should be replicated in future phases.
However, once you modify something in planning 2018, you should not change planning 2017 as we have not developed any rule for those cases. That's why we decided that once a planning 2017 is closed, it cannot be opened again and everything must be continued in planning 2018.

Did I respond your question?

**Comment by Grant-Lay** [comment]
@htobon @cgarcia9106 - Thanks for answering.  I am noticing some behavior where despite the original data entered in 2017 planning phase being carried over to the 2018 phase, updates in 2017 planning phase are not being carried over to the 2018 planning phase.  Note that we have not opened 2018 planning phase yet, I am simply viewing the data in read-only mode due to the 2018 phase being closed.  Make sense?  

I suppose in these cases, these are bugs that should be reported if the requirements are to update future phases too.  Perhaps their should be constraints on the system not allowing previous phases to be opened once a future phase of the same type (i.e. planning) is opened?  Otherwise you are going to get a lot of confused and frustrated users  :-)
