### ISSUE TITLE
sessionFactory.getCurrentSession().refresh(entity) should be removed

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1310]
The sessionFactory.getCurrentSession().refresh(entity) in the AbstractMarloDAO is not required within MARLO and should be removed.  This has the potential to trip up developers, as it removes any changes to the entity and brings the state up-to-date with the database.  

For example the code in the ProjectMySQLDAO does the following:

`@Override`
  `public Project find(long id) {`
   ` Project project = super.find(Project.class, id);`
   ` project = super.refreshEntity(project);`
    `return project;`
 ` }`

There is no point in doing the refresh as the Project entity has already been retrieved from the database.  

The refresh method therefore in the AbstractMarloDAO should be removed from the codebase as it could cause problems if developers do not understand what it does (any unsaved changes would be discarded for example).

**Comment by cgarcia9106** [comment]
https://github.com/CCAFS/MARLO/commit/1bbee7bcfc293cc2b266b343e93094ca63dce7f8

**Comment by htobon** [comment]
Hi @Grant-Lay. 
Here is our rationale about why we were doing this process, kindly let us know if we are missing something.

We understand that this function "super.find(Project.class, id);" retrieves the information of a project based on its ID directly from the database **or, if this project has changed in the current session, the information that is there will be retrieved and not the one that is in the database**.
Having said the above, when we call the method "find", we always want to retrieve the information that is currently in the database, that is why Christian included the function "super.refreshEntity(project);".

So, when you say: "There is no point in doing the refresh as the Project entity has already been retrieved from the database."
We don't think this is correct. As the information may have retrieve from the session and not from the database.

EXAMPLE:
1. We get the project P7 from the database and then, during the execution time we change its title.
2. Then, at some time in the execution work-flow, we would like to get the information from P7 that is in the database (again). 
3. So, when we call the method "find", it will bring us the P7 with the title changed. Which we don't expect.

Does it make sense?

On the other hand, Christian mentioned that he deleted the code (as you suggested - see commit above) because in this process, it seems all the actions are more adapted to the new Hibernate transactional process that you implemented. However, we are not sure it is working as we expect, so we would need to monitor and check that MARLO is working properly. 

If at the end, we some issue is presented, we will have to go back and include those lines of code. And we will communicate this to you so you can help us implement a proper solution.

If everything is ok here, can you please close this issue?

**Comment by Grant-Lay** [comment]
@htobon @cgarcia9106 - So basically you want to be able to ignore the first level cache that hibernate is maintaining.  I am trying to think of a business requirement that the same user (FYI other users sessions are not updated -they continue to get the database version until the update is applied) in the same request would want to get the version of the entity after they have already started updating it.  That is a strange requirement, right?   

Perhaps as you suggest the perceived need for this is a legacy of the previous MARLO architecture?  The danger of course is that if a piece of code does a find of entity P7 (they shouldn't need to, but suppose they did) and refresh is called then any unsaved changes to the entity will be discarded.   That is something we definitely want to avoid.

Closing this now.
