### ISSUE TITLE
CIAT MARLO - Re-vamp Projects and Funding sources (aligned with CRPs format)

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1347]
o	Stabilize functional and technical The CIAT MARLO Impact Pathway Section.
o	Organize CIAT MARLO texts using the internationalization files.
o	CIAT MARLO Projects and Funding Source functional Specificities.
o	Stabilize functional and technical The CIAT MARLO Outcomes and CapDev Sections.

**Comment by mralmanzar** [comment]
This issue will close because is related with:
- Stabilize functional and technical The CIAT MARLO Impact Pathway Section. https://github.com/CCAFS/MARLO/issues/1479
- Organize CIAT MARLO texts using the internationalization files. https://github.com/CCAFS/MARLO/issues/1494
- CIAT MARLO Projects and Funding Source functional Specificities. https://github.com/CCAFS/MARLO/issues/1349
- Stabilize functional and technical The CIAT MARLO Outcomes and CapDev Sections.  https://github.com/CCAFS/MARLO/issues/1352
