### ISSUE TITLE
Create a function to "Expand/Collapse" project funding sources per Partner

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1736]
![fs_expand_collapse](https://user-images.githubusercontent.com/4406128/52442846-3881e580-2af2-11e9-99ef-c25ec94fa1d9.gif)

**Comment by htobon** [comment]
Hi Sebas, 
I think Pascale meant to say that we should collapse the entire partners block.
"Finally, it would be much more convenient if by default the FS were hidden, and then the list of FS by partner would expand when we click on a partner?"

Something like the following image:
![image](https://user-images.githubusercontent.com/5375915/52451449-0cc02900-2b0d-11e9-9f9d-0bc06da003e5.png)

Therefore, since you already developed the expand/collapse functionality in the list of Funding sources, please keep it but implement a general one for all the partners.

What do you think?

Happy to talk.

**Comment by htobon** [comment]
I have just asked Pascale if this is ok.
Cheers.
