### ISSUE TITLE
Guest Users Module

### ISSUE THREAD

**Issue by kenjitm** [CCAFS/MARLO#1802]
- [x] Implement validations
- [x] Allow add guest role to existing users

**Comment by kenjitm** [comment]
Its duplicated with #1814

**Comment by kenjitm** [comment]
The guest user module is created, and validations are implemented for Superadmin interceptors in MARLO. Both the creation of new guest users and the guest role assignment are enabled

![image.png](https://images.zenhubusercontent.com/5b743d40a6afdd0ad0617092/c8b15e36-3391-43cb-b672-ffdc7ed9834d)

**Comment by htobon** [comment]
Hi @kenjitm, here are some suggestion to improve the module:

- [ ] Please adjust the automated email as per the following screenshot. Please make sure the TO and BBC are correct because the example you sent me was wrong:
![image](https://user-images.githubusercontent.com/5375915/60839157-10c2a680-a192-11e9-801d-6a2c64219de7.png)

- [ ] Please adjust subject to: "[MARLO] You have been assigned a Guest role in A4NH"

- [ ] Please take out the word MARLO:
![image](https://user-images.githubusercontent.com/5375915/60839228-423b7200-a192-11e9-85bd-ba33a72c7358.png)

- [ ] According to the MARLO look and feel, the negative messages are colored in Yellow or Red. If the user could not be added for any reason, the message should not be green. Please ask @sebas932 the best practice for error messages.
![image](https://user-images.githubusercontent.com/5375915/60839274-67c87b80-a192-11e9-8260-954990a7fd72.png)

- [ ] I filled the email and then hit the "Add user" button. Then I got a message saying that the information was correctly saved... This is not true. Please adjust the message accordingly.
![image](https://user-images.githubusercontent.com/5375915/60839467-de657900-a192-11e9-9639-a1b4fafd5634.png)

- [ ] Success message should reads as: "The guest user role was assigned successfully"
![image](https://user-images.githubusercontent.com/5375915/60839638-4025e300-a193-11e9-9213-e793fb9c1fb9.png)

**Comment by kenjitm** [comment]
The activities indicated in the feedback were carried out.
The front end part is pending regarding the colors of the messages.

**Comment by htobon** [comment]
Hi @kenjitm, can you please let us know the status of this issue?
In the quick meeting of today, you mentioned that all issues were tackled, however, not all the comments are marked as checked above.

Therefore, I am moving this issue as "New" meanwhile you clarify.

Cheers,
Hector.

**Comment by kenjitm** [comment]
Hello @htobon 
The pending comments were reviewed, they are now fully covered. The changes in Marlodev are updated for testings.

**Comment by htobon** [comment]
Thank you @kenjitm, please release it to production and close this issue when it is done.
