### ISSUE TITLE
[MR][Project Page] Create a Project page in the CCAFS website

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO#1868]
The idea here will be to export the MARLO projets information into the CCAFS website.
In order to do this we will develop a service so the CCAFS website can get the detailed information  of a particular project in CCAFS in an automated way. We will develop this service in a progressive way. 
We will also document the process. 

- [x] Create mock-up 
- [ ] Contact the Macaroni Bros and inform them what we want to do for this new develop 
- [x] Develop a 1st JSON with the basic information (Id, Title, Summary (Description), Start Date, End Date, Flagships, Program Regions) 
- [ ] Add the information of the Project Location and Project Clusters of Activity Information.

**Comment by MargaritaRamirez** [comment]
Develop the service in MARLO: create a Json with a protocol for the CCAFS web-site (HJ) -draft

**Comment by MargaritaRamirez** [comment]
1st Update: 
Implemented a basic project information JSON structure that contains the following information:
•	Title
•	Summary (Description)
•	Start Date
•	End Date
•	Flagships
•	Program Regions
•	Cross Cutting Dimensions
•	Gender Analisys

![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/c99348cb-0efd-4ca5-a5e3-132a08ab3520)

**Comment by MargaritaRamirez** [comment]
1. We identify that some of the information that we want to bring from MARLO is in CCAFS website project so we sent to Marissa an email with the discrepancy that we find in both sites and inform her that is better to have only one source of information (primary source) and we want that MARLO is the one. 
We are waiting for her comments. 

2. Add the information of the Project Location and Project Clusters of Activity Information: In this sprint the back-end could not advance in the development because they have had a lot of work with critical issues that need to be fixed urgently.

**Comment by MargaritaRamirez** [comment]
We sent an email to Marissa with the projects that we have in MARLO in the upkeep 2019 section for the comms team to help us relate the URL so we can compare one-by-one the differences between projects.

**Comment by MargaritaRamirez** [comment]
We will have a meeting with the comms team on November 25 and present what we want to do with this project and explain them why is so important that they link the correct URL for the project in MARLO so we can document the process and try to understand who is going to be our information source. 
This are the themes that we are going to present in the meeting: 
1)	Tell people what’s coming
2)	Show them the mock-up and get their feedback – this is important as they are the ones who primarily deal with the project pages and they may have ideas about what is missing or what is unnecessary
3)	Introduce the process as we have outlined it so far (not very far at the moment as I understand it but we can just say it’s a work in progress!)
4)	Introduce the list of projects, which now has people’s names assigned to each project so that they can check for a project page for each one and add the URL to the spreadsheet
5)	Give them a deadline for checking for project pages – I will leave this up to you! Once you’ve selected one add it to the agenda so it’s clear

**Comment by MargaritaRamirez** [comment]
On Dec 9 we had a meeting with Marissa, Hector and David to discuss what will be the process to update the information and we decide: 
1. The comms team could review the information in MARLO and make the changes that they need before sending the information to the project page
2. How can we include hyperlinks in MARLO fields (description field)
3. Marissa will check what would be the ideal word limit for project description 
4. Margarita will update the mock-up: delete the CoA section and add Activities (only shows the titles)
5. Develop something in MARLO to turn off the submission of the information in the CCAFS website for those projects that don't need page. 
6. Shows on-going and completed projects

**Comment by MargaritaRamirez** [comment]
In our last meeting on Feb 4 with Marissa, David, and Hector we decide to: 
- Marissa to include the mockup in the whole revamp of the website for the core team. 
- We will work with the Annual Report section. 
- Marissa and the comms team will select which project they want to show on the website.

**Comment by MargaritaRamirez** [comment]
We coordinate a meeting with Diego and Hector to review what we have so far developed for the project page and discuss possible improvements before passing the information to the Macaroni Bros, according with the Macaroni meeting last week.

**Comment by Edwin0307** [comment]
We decided to close this issue because is too big and we are going to work more specif points the next time.
