### ISSUE TITLE
[DP] (CLARISA) Get Innovations List

### ISSUE THREAD

**Issue by yeyo2k3** [CCAFS/MARLO#1941]
On clarisa obtain a list of innovation by Year, Phase and CGIAR Acronym.

[x] Explain fields that we show on JSON
[x] Create service 
[ ] Testing Service

**Comment by yeyo2k3** [comment]
I create a innovation list with the same structure of getting an innovation by id, but in this case parameter to recieve is global Unit data (CRP, Plataform) ,Phase (AR, POWB) and year

@mralmanzar can you test it please and inform me  if something happens. thank you

**Comment by htobon** [comment]
Hi @yeyo2k3, I think @mralmanzar will be quite busy the following week. Is there anything here I can help? Or is any other person in the team that can help you to test? Perhaps @HermesJim and/or @kenjitm?

Kindly let me know your thought on this.

**Comment by yeyo2k3** [comment]
Ok, @HermesJim can test it too. I assign him to do  this.

**Comment by HermesJim** [comment]
Hi @yeyo2k3 

The services works, tested with POSTMAN, but I was check the code and seen some Services have a wrong REST Service Type permission.
for example in innovations, you assigned READ PERMISSIONS in the delete function, that's wrong because the request DELETE isn't a read function. (See the Image)
Please can you organize the permissions according of the service functionality. 
You can view the **RESAT API permissions** inside of Permissions.java. 

![image.png](https://images.zenhubusercontent.com/5798ae8de40e5714b16c9812/1514c39e-641b-4ace-ae3b-15f894e3a471)

Regards.

**Comment by HermesJim** [comment]
If do you like, close this issue because the services works fine (using a super admin account) and create another issue with the goal to organize the REST API Permissions in Innovation and maybe check the others CLARISA services.

Regards :)
