### ISSUE TITLE
[MR] (AICCRA) Review and adjust the Legal terms and conditions of MARLO-AICCRA

### ISSUE THREAD

**Issue by MargaritaRamirez** [CCAFS/MARLO#2332]
Review all the information of Legal Information in MARLO 

![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/2eda7b8d-ebce-4760-9751-4a87fa66601b)

**Comment by MargaritaRamirez** [comment]
@htobon here are some relevant points that I found in the Legal information from AICCRA page 

**PRIVACY POLICY**
- [ ] There is a paragraph that needs to be check and validate if we need to update the information for Alliance Bioversity International and CIAT 

![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/342a0e7c-203c-4dc2-83a8-1e8b9f077569)
 
- [ ] We are not using this 
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/c8e8a01e-5b62-4022-8bae-d3be949d3d2d)

- [ ] Should we need to update this to Alliance Bioversity Intenational and CIAT?
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/c7b83504-90db-4dbd-9afe-fe8b284257aa)

- [ ] Validate if this is working for AICCRA 
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/27882bb0-2545-4c71-95d2-6beae3681e54)

- [ ] Will this apply for AICCRA
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/e4cca17b-2837-47a2-b2cf-1898abf0b98e)

- [ ] Should we need to update this?
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/f52e32f1-fac0-4a43-a818-c1de2b0ff111)

TERMS AND CONDITIONS 

- [ ] Update the URL 
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/517d439c-1abf-4a01-84fe-278c907ab529)  @kenjitm 

- [ ] Are we going to use this information for AICCRA?
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/2b310e6f-6038-4d91-ad51-68bb8986526a)

- [ ] Validate if is the actual version 
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/e9b3635c-d640-47f2-a7c3-46c025d57e5a)

- [ ] will this remain or we need to contact the legal office
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/0a0f4766-570e-46a6-a7ac-fb5e1e3cca4e)

- [ ] update to Alliance? 
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/064083bd-58e7-4e0e-927e-98e559c8457e)

**Comment by htobon** [comment]
@MargaritaRamirez thanks Margarita. 
Now that we have identify the pieces that would need to be adjusted, can you please put them all together in a word document and propose adjustments in track chances? This way I will be able to take a look at them and accept them or reject them and propose an alternative.

Thank you in advance.

**Comment by MargaritaRamirez** [comment]
@htobon you can access the document 
https://cgiar.sharepoint.com/:w:/s/CCAFS-KDS/EbfB9oymxnJClhmK0fSom24B1TN_uBiZNBquzYXGjTlyxw?e=M73GQ4
D:\CGIAR\CCAFS-KDS - Documents\1_Projects\1_11_AICCRA\Data Management

**Comment by htobon** [comment]
Hi @MargaritaRamirez, thanks for providing this detailed review.
Here is what I propose you should do:
1. Please go ahead with the suggested adjustments. One of the things that we should focus is to understand, from a legal perspective, how should we name CIAT and the Alliance. This is something you can figure out directly with Julian or with someone who may be more familiarized with contracts management.
2. Once we have a solid version of the text, we should just replace it in our testing and production environment.
3. At the same time, it would be great if you can please find someone from the Alliance Legal department who can just check that everything is ok. This terms and conditions can be used by our team to also make them available in other tools that we are developing such as CLARISA, QA and the Submission tool.

I hope this makes sense to you.

**Comment by MargaritaRamirez** [comment]
@htobon made some adjustments once you reviewed I will contact the legal office

**Comment by htobon** [comment]
Hi @MargaritaRamirez, I have taken a look once again, have approved and rejected some of your proposed adjustments and also include some comments for your review. I have also adjusted some texts directly in the document without doing track changes so that we expedite the process of having a clean version.

I think the more challenging part at the moment is to create a paragraph which can explain the way how Tawk.to is managing the data as this is one of the main services that we are using in our system and that is collecting personnel information. We should also mention that we are not sharing emails with them (please ensure this is the case with @kenjitm @gcmartinezg and others).

The current version is ready to be shared with our legal department. Please feel free to do it and tell them that we have included a lot of comments for them to review. The most common one are the institution name as we should no longer be called as CIAT but as the Alliance between Bioversity and CIAT.

So, based on this, I will proceed to send a request to the Legal office at the Alliance and seek for their help to improve the document.

**Comment by MargaritaRamirez** [comment]
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/2be5df19-a074-433b-9826-fd78858a886b)

**Comment by MargaritaRamirez** [comment]
![image.png](https://images.zenhubusercontent.com/5c6c4b4e3ba63a679b1c58cc/a635429f-9ed6-4f2a-8c1c-c12bfd2d3556)
