### ISSUE TITLE
Improve pentaho reports design

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#384]

**Comment by htobon** [comment]
@AndresFVR please give us an example so I can review it. Thks.

**Comment by AndresFVR** [comment]
Project without data
[project_full(no data).pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/project_full%28no%20data%29-265d0b9bf513f8f8a820e6b7a3c82b3eadc3961b27b26482a62b94400e7feb39.pdf)

Submitted project
[project_full.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/project_full-af765f84f31ea290745036f49523c04e2d5d3d20a723303b46c9d464b5e53414.pdf)

**Comment by htobon** [comment]
With regards **project_full(no data).pdf**:
- For those fields that don't have data, please use the sentence "<Not defined>".

With regards **project_full.pdf**:
- Flagship name should be its description and not "Flagship 2"
- Cluster of Activities are being showed on top of the previous section.
- Indeed, I think the title in black "Cluster of Activities" is not needed because there is already a title in the header of the table.
- There are different kind of font types in the text. A good idea would be to standardize them. And same for the different sizes.
- Please run the report using a real example, I saw some fields with contents as "asdadsad".

**Comment by AndresFVR** [comment]
This issue solve #460 
@htobon 
@AndresFVR  and @carios1usb updated the document style.

New project: [Full_Project_Core(New Project).pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Full_Project_Core%28New%20Project%29-20619c783b4ac7edd455d9ad0bfc3be4ced61c899c779396485030a26e6c06b6.pdf)

Unsubmitted Project: [Full_Project_W1W2.pdf](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Full_Project_W1W2-4b69a594bcca33b5a1a872626407328a94404695c16011440f7fbfbf7cf5d778.pdf)

Please review.

**Comment by htobon** [comment]
Closing this issue as will be followed-up in the issue #460
