### ISSUE TITLE
Rule: CRP Admin / Program Management / Remove PMU User

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO#467]
Rule: You cannot remove a person who is Management Liaison of at least one project. Instead, a message must be displayed with an explation.

Testing results: We could not test this rule as there is not a relationship between the PMU section and the Management Liaisons List.

**Comment by AndresFVR** [comment]
@htobon @cgarcia9106  The message could be 

This program managment user cannot be deleted due to the following reason(s): 
 - At least one or more projects are related with this managment liason.
 - If you want to proceed with the deletion, please go to projects and change the Management Liaison Contact Person.

**Comment by AndresFVR** [comment]
@cgarcia9106  i tried to remove the user and this message is shown.
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2df6f67bbe78ef3946bacf50182c912d15c982db77cff00d3752571a66f2f71b.png)

**Comment by sebas932** [comment]
checked

**Comment by AndresFVR** [comment]
Added to Rules document
