### ISSUE TITLE
create interface to request a new partner

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#621]

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-db840b6308d77bc0091e61c1182b97dc7dabd7b53595a9c35c0620a3b52d1c0e.png)

**Comment by htobon** [comment]
Hi @carios1usb, please take a look at my comments below:
- Acronym field is optional
- Instead of "If you know the partner web page please......" please replace it for "Website"
- In the website link, instead "https://" please put "http://" (without the 's').

We also need to provide instructions for our best practices on how to name add new partners into our system:
1. Please enter the institution as “Partner,” the legal entity.  
2. The name of the institution should be in its official language. (e.g. For CIAT: Centro Internacional de Agricultura Tropical).

**Comment by htobon** [comment]
Please also include the following text in the help text box:
>Partners can be individuals and organizations that we work with to generate our outputs and products and to interact with next-users.
•	Expertise, network and influence with next-users.
•	Implementers.
These can be 1) budget receiving partner to lead an activity or 2) budget receiving partner contributing to implementation of parts of an activity or 3) only leverage funding providing implementation partners or 4) a combination of any of the three afore mentioned.

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-8c0ebce38a08bb5c0d2f11282e72751e25ef2b5c7721c56966127b52cb900c66.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-bba9fa5e21e0f53d6ee522732e9d130b7caa997d4beaa0ef440ea1e4606f7be5.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ca923574f04a0700ed89029da15a79607b862be20ff6480f2c79d1f8368a1d27.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b80f86d2a8237210013d10cdfcde88bb6b8a420cab9f072b43310e020fbd06d1.png)

**Comment by cgarcia9106** [comment]
![request partner email.PNG](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/request%20partner%20email-82aac3799063d650dc4be5a336ac402020265854c727655c3ebf14ef0b22bf38.PNG)
