### ISSUE TITLE
Develop a REST-API and share the current list of institutions

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO#982]
Develop a REST-API system in MARLO that allow the system to share the current list of institutions (as first step).

**Comment by Grant-Lay** [comment]
I've been working on authorization for the web service and have encountered some short comings in the struts2 rest plugin.   MARLO's authorization model requires that a user has either a CRP or Center in the HTTP session in order to grant authorization (roles are linked to the CRP or Center so this makes sense).  I originally wanted to register a single role called 'external system' with each CRP and then the rest URL would contain the crp id within the URL for example /api/fta/institutions.   This unfortunately doesn't work as the struts2 RestActionMapper assumes the 'fta' part of the URL is an id and a 404 page not found error ensures. So instead I have decided as a interim solution (pending struts2 rest plugin changes) to just register a single role ('external systems') and the big data platform will be the CRP that an external system user who wants access to our MARLO data, registers with.

**Comment by Grant-Lay** [comment]
The authorization logic has now been committed to the dev_add_marlo_web-services branch

**Comment by Grant-Lay** [comment]
@htobon let's perhaps talk about when we want to release this (I understand you have your hands full at the moment).   The more I use the struts rest plugin the more limitations I am discovering (for example this one detailed here https://stackoverflow.com/questions/17484179/struts2-restful-mapping-configuration), so much so that I think we should perhaps only make the webservices read-only. 

I recently discovered that struts2 has an exclude pattern which could potentially allow us to run a struts2 webapp and a spring webservice side by side.  I will investigate this today.

**Comment by Grant-Lay** [comment]
See the following commit which successfully ports across our REST webservices from struts2 to Spring.  https://github.com/CCAFS/MARLO/commit/4b3773e50e21312dfa5ec983d135396a649a5020

I've also added some validation using JSR 303 annotations to the DTOs.

Still a few things I want to do before we close this:

1.  See if we can hook up Swagger for REST api documentation (this was not possible using struts2-rest-plugin.
2.  Provide a more fine grain authorization model, where individual methods can be annotated with one of api:get, api:post, api:delete and api:put rather than at the moment api:*
3.  Provide a better exception handling framework so the user doesn't get a stacktrace but a more understandable message.
4.  Provide some unit-tests to ensure the web-services work and stay working.  We can look at mocking the DAOs until we sort out an in-memory test database.

**Comment by Grant-Lay** [comment]
@htobon what do you think about if we change the urls to be /api/{crp}/institutions and /api/{crp}/flagships etc?  Each CRP can grant access to the REST client that wants to consume the services rather than registering them under BigData which is what I have done at the moment.

**Comment by htobon** [comment]
Hi @Grant-Lay, please go ahead. The URL convention that propose is ok. thks!

**Comment by htobon** [comment]
Hi @Grant-Lay, could you please let us know any advance on this module?
This is becoming more and more important for MARLO.
Thank you in advance.

**Comment by Grant-Lay** [comment]
@htobon - sorry been busy with getting FTA entered so haven't had much time to progress this.  I want to slightly modify the DTOs for the institutions so that they match what the add new institution pop-up asks for and then I think we can merge this into staging.  The documentation is up and going, although we might want to disable it for production so that nothing untoward happens (not likely given each REST method requires authentication and authorization, but better to be safe).

**Comment by Grant-Lay** [comment]
I'm going to move this to review/QA as I've tested the services and they are all working.  I am buliding some unit-tests at the moment, but as I need to build a working unit test framework this will take a little time and I don't want to hold things up.

**Comment by htobon** [comment]
Hi @Grant-Lay, this is so great!
I'll talk with the team in order to check this functionality in the system and will get back to you in case of any questions. Hope this is ok.
Cheers!

**Comment by Grant-Lay** [comment]
I forgot to mention, to see the swagger documentation and test out the webservies go to (subsitute your host and port values):  

https://{host}:{port-number}/marlo-web/api/swagger-ui.html

We could think about having a link to this in the MARLO struts2 UI.

Using @htobon's account you will have access to everything.  I have created two other users *mel-system@no-reply* and *my-cifor@no-reply* who have read-only access to all rest web services plus the ability to request new institutions.  We need to change the password for their accounts in production after the flyway scripts have been run.  Every other user will get a 403 unauthorized for all operations.

**Comment by Grant-Lay** [comment]
Upon checking to see if new institutions appear in the request institutions struts page, it appears that new institutions are not saved in the institutions table but in the partner_requests table (not sure why this is done in a separate table?).

I guess I will need to change the behaviour of the create new institution functionality to use the PartnerRequestManager rather than create a new institution without having it verified.

**Comment by Grant-Lay** [comment]
@htobon - I have changed the create institution method to add a new PartnerRequest instead of an Institution but I need your help.  It seems that only partnerRequests with a partner_request_id (self refrentrial) column get displayed in the screen.  I have no idea what to populate this column with (or am I supposed to create two rows???).  Can you please let me know how to proceed with this.

**Comment by AndresFVR** [comment]
Hi @Grant-Lay, 
This is how 'Request Institutions' works.

For an institution request:

1-Parent: It is used to know what was requested by the user. It will not change.
2-Child: It is the request that is edited, accepted or rejected by the Admin and it references to the partner request with the column partner_request_id.
We insert two rows per request in order to know what was requested and what was accepted/declined.. 
As you said, the only partnerRequest with partner_request_id get displayed in the screen.

For the other hand, we have country offices request (it doesn't have partner_request_id but get displayed)
We insert only one row per request because we just accept/decline but we don't edit the request.

Please refer to the following screenshoot of the Request Institutions interface:
https://www.screencast.com/t/xdYrWegso9k2

**Comment by Grant-Lay** [comment]
Thanks for the explanation @AndresFVR.  I can go ahead with this now.

**Comment by Grant-Lay** [comment]
@htobon - Do I need to close this now or do I wait for it to be released to production?

**Comment by htobon** [comment]
Hi @Grant-Lay, let's wait until this is released into production.

**Comment by htobon** [comment]
Hi @HermesJim, can you please let us know the status of this module in the production environment?

**Comment by HermesJim** [comment]
Hi @htobon .
I try to acces to the API using the url (https://marlo.cgiar.org/api/swagger-ui.html) but returns me a 404 error page, sometimes show me a popup ask me an usermane and password, I writed my MARLO acount but does not still work, throws again the 404 error page.

Hi @Grant-Lay                        ,
Am I doing the process to access to the API correctly?
and please, could you help me get into context, is there any documentation of the implementation of the REST API with which I can be guided?

**Comment by Grant-Lay** [comment]
@htobon & @HermesJim.  I disabled swagger in production as it could be a potential security issue but it is enabled on local developer machines and the test environment https://marlodev.ciat.cgiar.org/api/swagger-ui.html, you will need to login with a user that has permissions to invoke the api for the particular globalUnit.

**Comment by HermesJim** [comment]
@Grant-Lay                        

Great, It Worked in MarloDev.

I checked in the database, that you created a Role (External System) for the REST-API access.
Could we find sometime for you to explain me how did you integrate the Apache Shiro Permissions with the REST-API?
please feel free to chat with me in Slack.

Thank You.
